### PR TITLE
Fixed DO_pct standard name. Caused problems when creating csv files from

### PR DESCRIPTION
**Pull request by ebridger**
paegan response object, duplicate dict keys. Also fixed the salinity
units, ppt to psu. Checked both in CDMO Manuals and CF standard names
table.

### CODE REVIEW

**Comment by ebridger** [comment]
Changed:
 
` 'DO_pct'    :       'oxygen_concentration_in_sea_water'`

to 

` 'DO_pct'    :       'fractional_saturation_of_oxygen_in_sea_water`
 
Also fixed salinity units, ppt to psu

**Comment by emiliom** [comment]
This looks good to me. I'll merge. Thanks @ebridger

**Comment by emiliom** [comment]
Ok, I won't merge -- I forgot that I'm not admin here.

@ocefpaf, can you merge? BTW, the Travis-CI failures seems to be unrelated. This commit is straightforward.

**Comment by emiliom** [comment]
Thanks @ocefpaf

**Comment by mwengren** [comment]
@ocefpaf Thanks.  We need to come up with a better plan to keep some eyes on this and some other repositories so PRs like this don't languish.  I don't know that we have the bandwidth here.

cc: @Bobfrat @kknee

**Comment by ocefpaf** [comment]
I find the GitHub feature to request a review helpful with that, or even a "ping" like @emiliom did here.

Although, for this particular repository, I guess that the question is: for how long to we want to maintain `pyoos`?

**Comment by emiliom** [comment]
> Although, for this particular repository, I guess that the question is: for how long to we want to maintain pyoos?

That would be a topic of broader interest, that ideally should be broadcast to a broader audience; say, the ioos_tech group, and/or the DMAC meeting in May.

**Comment by ebridger** [comment]
Probably my fault for not "pinging"  but it wasn't clear who to ping.

**Comment by Bobfrat** [comment]
I just changed my preferences to be notified of all activity on the repo so I'll keep an eye on it

**Comment by ocefpaf** [comment]
> Probably my fault for not "pinging" but it wasn't clear who to ping. 

You can use `Reviewers` option on the top left and see who GitHub suggests.

**Pull request merged**
