### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by ocefpaf**
Preparing a new release. Again, self-merging this one as it is (mostly) harmless.

### CODE REVIEW

**Comment by lukecampbell** [comment]
:+1:

**Comment by lukecampbell** [comment]
Can someone push the relase to pypi?

**Comment by ocefpaf** [comment]
> Can someone push the relase to pypi?

I already did conda btw: https://github.com/conda-forge/pyoos-feedstock/pull/3

@daf can we do "teams" in `PyPI`?

**Comment by daf** [comment]
@ocefpaf I don't know if PyPI has the concept of teams.  You're already a "maintainer" btw, so I think you can upload new releases.  I'll do this one though.

**Comment by ocefpaf** [comment]
I will try the next one then. Thanks @daf!

**Pull request merged**
