### PR TITLE
hads collector update to support unverified SSL certs

### PR DESCRIPTION
**Pull request by emiliom**
Added kwargs to hads collect method, to support optional, user-driven `verify=False` option/argument to be passed to requests (to handle failing HADS SSL cert). Tested successfully.

Implemented only on methods called directly by the `collect` method. Other `requests` calls may need to be updated similarly, for completeness and full functionality.

### CODE REVIEW

**Comment by emiliom** [comment]
Should I withdraw the PR and submit a new one, to handle (remove) the unintended changes?

**Comment by emiliom** [comment]
I added a commit that removed the unintended changes (regressions). It's ready for review on this PR. I tested it on Python 2.7.

As before, only the hads collector file is impacted.

**Comment by emiliom** [comment]
Has anyone had a chance to review my updated PR from 20 days ago?

FYI, I'm using it operationally (from my pyoos fork) for automated hads data harvesting.

**Comment by lukecampbell** [comment]
btw, we're in contact with NCO and they're working to fix the certificate issue

**Comment by daf** [comment]
I'm good with it, I like that it makes the use explicit from the pyoos user, not hidden inside of pyoos itself.

@lukecampbell ?

**Comment by emiliom** [comment]
Thanks @daf!

**Comment by emiliom** [comment]
Great, thanks @lukecampbell!

**Pull request merged**
